# -*- coding: utf-8 -*-
"""
Tất cả câu SQL – tập trung tại đây để dễ sửa.
Các module import từ đây thay vì hardcode.
"""

# --- WIP ---
WIP_GET_STATION_AND_NEXT = """
SELECT A.SERIAL_NUMBER, A.MO_NUMBER, A.MODEL_NAME,
       A.STATION_NAME, A.LINE_NAME, A.GROUP_NAME,
       (SELECT R.GROUP_NEXT FROM SFIS1.C_ROUTE_CONTROL_T R
        WHERE R.ROUTE_CODE = A.SPECIAL_ROUTE
          AND R.GROUP_NAME = A.GROUP_NAME
          AND R.STATE_FLAG = A.ERROR_FLAG
          AND ROWNUM = 1) AS NEXT_STATION
FROM SFISM4.R_WIP_TRACKING_T A
WHERE A.SERIAL_NUMBER = :sn
"""

# --- Repair ---
REPAIR_CHECK_UNREPAIRED = """
SELECT COUNT(*) FROM SFISM4.R_REPAIR_T
WHERE SERIAL_NUMBER = :sn AND REPAIR_TIME IS NULL
"""

REPAIR_UPDATE = """
UPDATE SFISM4.R_REPAIR_T
SET REPAIR_TIME = SYSDATE,
    REASON_CODE = :reason_code,
    DUTY_STATION = :duty_station,
    DUTY_TYPE = :duty_type,
    RECORD_TYPE = :record_type,
    REPAIR_ACTION = :repair_action,
    REMARK = :remark,
    REPAIRER = :repairer,
    REPAIR_STATION = :repair_station
WHERE SERIAL_NUMBER = :sn AND REPAIR_TIME IS NULL
RETURNING REPAIR_TIME INTO :repair_time
"""

REPAIR_GET_GROUP_INFO = """
SELECT * FROM (
    SELECT DISTINCT T3.LINE_NAME, T3.SECTION_NAME, T3.GROUP_NAME, T3.STATION_NAME, '1' AS RRR
    FROM SFIS1.C_SECTION_CONFIG_T T1
    LEFT JOIN SFIS1.C_GROUP_CONFIG_T T2 ON T1.SECTION_NAME = T2.SECTION_NAME
    LEFT JOIN SFIS1.C_STATION_CONFIG_T T3 ON T1.SECTION_NAME = T3.SECTION_NAME AND T2.GROUP_NAME = T3.GROUP_NAME
    WHERE T3.GROUP_NAME = :g AND T3.LINE_NAME LIKE '%' || REGEXP_REPLACE(:l, '[^0-9]', '') || '%'
    UNION
    SELECT DISTINCT :l AS LINE_NAME, GROUP_NAME AS SECTION_NAME, GROUP_NAME AS GROUP_NAME, GROUP_NAME AS STATION_NAME, '2' AS RRR
    FROM SFIS1.C_GROUP_CONFIG_T WHERE GROUP_NAME = :g
    ORDER BY RRR, LINE_NAME, STATION_NAME
) WHERE ROWNUM = 1
"""

REPAIR_GET_JUMP_PARAM = """
SELECT T1.GROUP_NAME FROM SFIS1.C_ROUTE_CONTROL_T T1, SFISM4.R_WIP_TRACKING_T T2
WHERE T1.ROUTE_CODE = T2.SPECIAL_ROUTE AND T2.SERIAL_NUMBER = :sn
  AND T1.GROUP_NEXT = :target AND T1.STATE_FLAG = '0' AND ROWNUM = 1
"""

REPAIR_JUMP_WITH_TIME = """
UPDATE SFISM4.R_WIP_TRACKING_T SET
(LINE_NAME, SECTION_NAME, GROUP_NAME, STATION_NAME, ERROR_FLAG, IN_STATION_TIME, EMP_NO) =
(SELECT :v_line, :v_section, :v_group, :v_station, '0', :in_time, :emp FROM DUAL)
WHERE SERIAL_NUMBER = :sn
"""

REPAIR_JUMP_SYSDATE = """
UPDATE SFISM4.R_WIP_TRACKING_T SET
(LINE_NAME, SECTION_NAME, GROUP_NAME, STATION_NAME, ERROR_FLAG, IN_STATION_TIME, EMP_NO) =
(SELECT :v_line, :v_section, :v_group, :v_station, '0', SYSDATE, :emp FROM DUAL)
WHERE SERIAL_NUMBER = :sn
"""

# --- Kitting ---
KITTING_FETCH_ASSY_TREE = """
SELECT
    SERIAL_NUMBER AS SN,
    FATHER_SN,
    SUB_MODEL_NAME,
    VENDOR_SN,
    TO_CHAR(
        (FROM_TZ(CAST(IN_STATION_TIME AS TIMESTAMP), SESSIONTIMEZONE) AT TIME ZONE 'America/Los_Angeles'),
        'YYYY-MM-DD HH24:MI:SS'
    ) AS IN_STATION_TIME,
    STACK,
    ASSY_FLAG,
    ASSY_SEQ
FROM SFISM4.R_ASSY_COMPONENT_T
WHERE SERIAL_NUMBER = :sn
  AND GROUP_NAME IN (SELECT GROUP_NAME FROM SFIS1.KITTING_GROUP_V)
ORDER BY ASSY_SEQ, VENDOR_SN
"""

KITTING_COUNT_DEKITTED = """
SELECT COUNT(*) FROM SFISM4.R_ASSY_COMPONENT_T
WHERE SERIAL_NUMBER = :sn AND ASSY_FLAG = 'N'
  AND GROUP_NAME IN (SELECT GROUP_NAME FROM SFIS1.KITTING_GROUP_V)
"""

KITTING_DEKIT_UPDATE = """
UPDATE SFISM4.R_ASSY_COMPONENT_T
SET ASSY_FLAG = 'N', IN_STATION_TIME = SYSDATE, EMP_NO = :emp
WHERE SERIAL_NUMBER = :sn AND ASSY_FLAG = 'Y' AND VENDOR_SN = :v
  AND (FATHER_SN = :f OR (FATHER_SN IS NULL AND :f IS NULL))
"""

KITTING_INSERT_SELECT = """
SELECT * FROM SFISM4.R_ASSY_COMPONENT_T
WHERE SERIAL_NUMBER = :sn AND VENDOR_SN = :old
  AND (FATHER_SN = :old_f OR (FATHER_SN IS NULL AND :old_f IS NULL))
"""

# --- Jump route ---
JUMP_GET_WIP = """
SELECT SERIAL_NUMBER, LINE_NAME, GROUP_NAME, SECTION_NAME, STATION_NAME, ERROR_FLAG, SPECIAL_ROUTE
FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = :sn
"""

JUMP_GET_ROUTE_LIST = """
SELECT T1.STEP_SEQUENCE AS STEP, T1.GROUP_NAME, T1.GROUP_NEXT, T1.STATE_FLAG AS FLAG
FROM SFIS1.C_ROUTE_CONTROL_T T1, SFISM4.R_WIP_TRACKING_T T2
WHERE T1.ROUTE_CODE = T2.SPECIAL_ROUTE AND T2.SERIAL_NUMBER = :sn AND T1.STATE_FLAG = '0'
ORDER BY T1.STEP_SEQUENCE
"""

JUMP_GET_GROUP_INFO = REPAIR_GET_GROUP_INFO  # Dùng chung

JUMP_CHECK_JUMP_STATION = """
SELECT * FROM (
    WITH TEMP_ROUTE AS (
        SELECT ROUTE_CODE, GROUP_NAME, GROUP_NEXT, STEP_SEQUENCE
        FROM SFIS1.C_ROUTE_CONTROL_T WHERE STATE_FLAG = '0'
        AND ROUTE_CODE = (SELECT SPECIAL_ROUTE FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = :sn)
        ORDER BY STEP_SEQUENCE
    ),
    TEMP_KITTING AS (
        SELECT ROUTE_CODE, GROUP_NAME, STEP_SEQUENCE FROM TEMP_ROUTE
        WHERE GROUP_NAME IN (SELECT GROUP_NAME FROM SFIS1.KITTING_GROUP_V)
    ),
    TEMP_TARGET AS (
        SELECT GROUP_NAME AS TARGET_GROUP, STEP_SEQUENCE AS TARGET_SEQ FROM TEMP_ROUTE WHERE GROUP_NAME = :g
    )
    SELECT * FROM TEMP_KITTING T1 LEFT JOIN TEMP_TARGET T2 ON 1=1 WHERE T2.TARGET_SEQ > T1.STEP_SEQUENCE
)
"""

JUMP_CHECK_ASSY = """
SELECT COUNT(0) AS CNT FROM SFISM4.R_ASSY_COMPONENT_T
WHERE ASSY_FLAG = 'Y' AND SERIAL_NUMBER = :sn AND GROUP_NAME = :g
"""

JUMP_ROUTING = REPAIR_JUMP_SYSDATE  # Dùng chung

# --- Repair fail flow ---
REPAIR_FAIL_HISTORY = """
SELECT
    r.SERIAL_NUMBER,
    r.TEST_TIME,
    r.GROUP_NAME,
    r.TEST_CODE                           AS ERROR_CODE_IN_REPAIR,
    e.ERROR_CODE                          AS ERROR_CODE_MASTER,
    e.ERROR_DESC
FROM SFISM4.R_REPAIR_T r
LEFT JOIN SFIS1.C_ERROR_CODE_T e
       ON REPLACE(e.ERROR_CODE, ' ', '') = REPLACE(r.TEST_CODE, ' ', '')
WHERE r.SERIAL_NUMBER = :sn
  AND NVL(r.RECORD_TYPE, 'T') = 'T'
ORDER BY NVL(r.REPAIR_TIME, r.TEST_TIME), r.TEST_TIME
"""

REPAIR_VALIDATE_ERROR_CODE = """
SELECT COUNT(*)
FROM SFIS1.C_ERROR_CODE_T
WHERE REPLACE(ERROR_CODE, ' ', '') = REPLACE(:ec, ' ', '')
  AND NVL(ERROR_TYPE, '?') IN ('E','W')
"""
